name: Heat Simulation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-heat:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PartA1 and save log
        shell: cmd
        run: |
          mkdir outputs\PartA1
          python scripts\run_heat.py --file src\PartA1.py --out outputs\PartA1 2>&1 | tee outputs\PartA1\output_log.txt

      - name: Run PartA2 and save log
        shell: cmd
        run: |
          mkdir outputs\PartA2
          python scripts\run_heat.py --file src\PartA2.py --out outputs\PartA2 2>&1 | tee outputs\PartA2\output_log.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: heat-outputs
          path: outputs/
